name: Build & Test - Zig 0.12.0

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  # Cancels pending runs when a PR gets updated.
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

jobs:
  build-and-test-stable:
    uses: ./.github/workflows/build-and-test.yml
    with:
      zig-version: 0.12.0

  build-and-test-stable-success:
    needs: [build-and-test-stable]
    runs-on: [ubuntu-latest]
    steps:
      - name: Success
        run: echo 'Success'
