name: Zig master

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        backend: [ncurses, crossterm]
        exclude:
          - platform: windows-latest
            backend: ncurses

    runs-on: ${{ matrix.platform }}
    if: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@2a9625d550eefc3a9b1a43d342ad655f563f8241
        with:
          version: master

      - name: Zig version
        run: zig version

      - name: Build all examples
        run: |
          cd examples
          zig build -Dbackend=${{ matrix.backend }} --summary all
          cd ..

      - name: Run all tests
        run: zig build test -Dbackend=${{ matrix.backend }} --summary all
